version: '3.8'

services:
  gift-api:
    container_name: gift-api
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USERNAME: root
      DB_MYSQL_PASSWORD: root
      DB_NAME: gifts
    networks:
      - gift-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gift-network

volumes:
  db_data:

networks:
  gift-network:
